# Generated by Django 4.2.6 on 2024-05-21 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
