# Generated by Django 4.2.6 on 2024-05-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_note_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
    ]
